import type { Metadata } from "next";
import "./globals.css";
import AuthProvider from "@/providers/auth";
import { Toaster } from "sonner";
import BookingProvider from "@/providers/booking";
import AIChatbot from "@/components/chatbot/chatbot";

export const metadata: Metadata = {
  title: "Ciel Power",
  description: "Generated by Ciel Power",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <BookingProvider>
            <Toaster />
            {children}
            <AIChatbot/>
          </BookingProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
